- .gitlab-ci.yml
- Makefile.toml
- qcs/examples/parametric_compilation.rs
- qcs/examples/quil_t.rs
- qcs/src/executable.rs
- qcs/src/qpu/execution.rs
- qcs/src/qpu/quilc/mod.rs
> feat: Add `compile_with_quilc` option on `Executable` to support Quil-T.

- qcs/src/executable.rs
- qcs/src/qpu/execution.rs
- qcs/src/qpu/quilc/isa/qubit.rs
- qcs/src/qpu/runner.rs
- qcs/src/qvm/execution.rs
- qcs/tests/mocked_qpu.rs
Closes #31
This basically introduces threads to run all the RPCQ connections inside of. As a result, there's some `Arc`ing and `Box`ing. This PR will result in a bit slower performance overall but I think it's well worth it to not block the runtime. Importantly, this also enables callers to use timeouts if they want to give up eventually rather than waiting forever.
> fix: Stop blocking the async runtime when connecting to quilc or a QPU.

- Cargo.lock
- qcs/Cargo.toml
- qcs/src/configuration/mod.rs
- qcs/src/configuration/path.rs
- qcs/src/configuration/secrets.rs
- qcs/src/configuration/settings.rs
- qcs/src/executable.rs
- qcs/src/execution_result.rs
- qcs/src/lib.rs
- qcs/src/qpu/engagement.rs
- qcs/src/qpu/execution.rs
- qcs/src/qpu/mod.rs
- qcs/src/qpu/quilc/isa/edge.rs
- qcs/src/qpu/quilc/isa/mod.rs
- qcs/src/qpu/quilc/isa/qubit.rs
- qcs/src/qpu/quilc/mod.rs
- qcs/src/qpu/rewrite_arithmetic.rs
- qcs/src/qpu/rpcq.rs
- qcs/src/qpu/runner.rs
- qcs/src/qpu/translation.rs
- qcs/src/qvm/execution.rs
- qcs/src/qvm/mod.rs
Closes #62 
BREAKING CHANGE: Changed the error types returned from all public methods.
> feat: Replace `eyre` with `thiserror` for all errors.

- qcs/examples/parametric_compilation.rs
- qcs/examples/quil_t.rs
- qcs/src/executable.rs
- qcs/src/execution_data.rs
- qcs/src/lib.rs
- qcs/src/qpu/execution.rs
- qcs/src/qpu/runner.rs
- qcs/src/qvm/execution.rs
- qcs/src/qvm/mod.rs
- qcs/src/register_data.rs
- qcs/tests/basic_qvm.rs
- qcs/tests/mocked_qpu.rs
- qcs/tests/parametric_compilation.rs
BREAKING CHANGE: The return type of `Executable::execute_on_qpu` and `Executable::execute_on_qvm` is a new `ExecutionData` struct. The previous result map is now stored on `ExecutionData::registers` with the renamed `RegisterData` type (previously `ExecutionResult`).
Closes #89
> feat!: Return billable QPU execution time in results.

- src/executable.rs
- src/lib.rs
Resolves #126.
BREAKING CHANGE: added `#[must_use]` to `JobHandle::job_id` at clippy's
suggestion.
> feat: export JobHandle and derive traits on it

- .github/workflows/prepare-release.yml
- .github/workflows/release-dry-run.yml
- .github/workflows/release-library.yml
- .github/workflows/release-python.yml
- .github/workflows/release.yml
- README.md
Fixes for the two workflows that failed after merging #145
[Release Dry Run](https://github.com/rigetti/qcs-sdk-rust/actions/runs/3055481949/jobs/4928586660) failed because it was still pointing to an old version of knope (was 0.4.1, now 0.6.1)
[Prepare Release](https://github.com/rigetti/qcs-sdk-rust/actions/runs/3055481949/jobs/4928586660) failed because `GITHUB_TOKEN` can't be used to push to a protected branch (and can't be configured to do so safely). I took inspiration from the release workflow and use the already configured `secrets.PAT` instead.
While looking at the `Release` workflow, I realized it should probably be following the same pattern for releases as the Python package, so I updated it.
> ci: use knope 0.6.1 in release dry run and secrets.PAT to auth with gh

- .github/workflows/release-library.yml
- .github/workflows/release-python.yml
`[skip ci]` applies to _all_ push events, including tag creation. This means that the tags `knope` creates don't trigger the workflows, since it pushes a `[skip ci]` commit right before.  
Setting these workflows up to run on `release` events instead. The `published` event triggers on pre-release and release creation, as well as when pre-releases are promoted to full releases. I also added `workflow_dispatch` as an option just so we have the flexibility of kicking these off on our own terms.
I've manually verified these with [act](https://github.com/nektos/act). 
```sh
act release --dryrun -e payload.json
```
Where `payload.json` is mocking the [release webhook payload](https://docs.github.com/en/rest/releases/releases#get-a-release) with `tag_name`
```json
{
"release": {
"tag_name": …
```
> ci: trigger releases on release events instead of tags being pushed

- crates/lib/src/qpu/quilc/isa/operator.rs
- crates/lib/src/qpu/quilc/isa/qubit.rs
- crates/python/src/lib.rs
See attached issue for details.
Closes #179.
> fix: deserialize null fidelity and duration as "perfect" values

- Cargo.lock
- crates/lib/Cargo.toml
- crates/python/Cargo.toml
`qcs-api-client` was requiring `grpc_api_url` to exist in `settings.toml`. `0.2.6` makes the value optional and prevents errors from occurring when it's not defined in operations that don't need it.
> fix: make grpc_api_url optional in settings.toml

- crates/lib/src/api.rs
- crates/lib/src/executable.rs
- crates/lib/src/qpu/execution.rs
- crates/lib/src/qpu/quilc/mod.rs
- crates/lib/src/qpu/rpcq.rs
- crates/python/qcs_sdk.pyi
- crates/python/src/lib.rs
Closes #209 
* `quilc::compile_program` now takes a `timeout: Option<u8>` parameter for overriding the default timeout.
* `Execution::new` now takes a `compiler_timeout: Option<u8>` parameter, since it calls out to `compile_program`.
> feat!: make compiler timeout configurable

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/qpu/client.rs
- crates/python/Cargo.toml
Remove `GATEWAY_ADDR` environment variable and fully paginate accessor results to find the highest priority Gateway.
> fix: Fetch Gateway address with pagination

- crates/python/qcs_sdk/compiler/quilc.pyi
- crates/python/qcs_sdk/qpu/api.pyi
- crates/python/src/compiler/quilc.rs
Should have been included in #255
- PyQuil defines it's own `TargetDevice` that has the same JSON representation of the `qcs_sdk` one, used for quilc compilation.
- `ExecutionResults` data is a register, lot a list of registers.
> fix: add missing types and fix others needed from pyquil

- .github/workflows/release-python.yml
- crates/python/pyproject.toml
From https://github.com/rigetti/qcs-sdk-rust/issues/258
Seems the issue may be specifically the 3.7 build path.
Since `pyproject` specifies that the required python version be `^3.8`, seems 3.7 support could be removed anyway.
> fix!: remove python 3.7 support

- Cargo.lock
- Cargo.toml
- crates/lib/src/qpu/client.rs
Closes #238 
Route requests through client proxies via `HTTPS_PROXY` and `HTTP_PROXY` environment variables.
Supported protocols are `http`, `https`, and `socks5`.
> feat!: support HTTPS_PROXY and HTTP_PROXY client proxies

- Cargo.lock
- Cargo.toml
- deny.toml
Fixes build failures after #266 was merged.
Removes `openssl-sys` dependency in favor of `rustls`
> fix: use qcs-api-client version with rustls and not openssl

- crates/lib/examples/delayed_job_retrieval.rs
- crates/lib/src/executable.rs
- crates/lib/src/qpu/api.rs
- crates/lib/src/qpu/client.rs
- crates/lib/src/qpu/execution.rs
- crates/python/qcs_sdk/_executable.pyi
- crates/python/src/executable.rs
- crates/python/src/qpu/api.rs
This is *one* solution to allowing `endpoint_id` to be provided when submitting a job, presented as a draft for discussion.
To consider, there is benefit in separating translation from submission, but if we keep all that functionality on `Execution` it's not straightforward to me how `Execution` would cache translation output between `submit`, or how it would be made clear that `translate` should be called before `submit`.
> feat: support endpoint_id job target

- crates/python/qcs_sdk/qpu/api.pyi
Accidentally missing from #262
> fix(python): missing endpoint_id param added to api type annotations

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/compiler/quilc.rs
- crates/lib/src/executable.rs
- crates/lib/src/execution_data.rs
- crates/lib/src/qpu/api.rs
- crates/lib/src/qpu/execution.rs
- crates/lib/src/qpu/mod.rs
- crates/lib/src/qpu/rewrite_arithmetic.rs
- crates/lib/src/qpu/translation.rs
- crates/lib/src/qvm/execution.rs
Resolves #263.
This adds tracing log statements in places where it seemed particularly useful to get a peek at what the SDK is doing.
This PR does not, at this time, include `TRACE` level statements or spans for every function/entrypoint. I wanted to open up discussion on whether we want that at this time. I see at least using `tracing::instrument` at the `TRACE` level on each function as potentially useful.
> feat: add tracing support

- crates/lib/src/compiler/quilc.rs
- crates/python/qcs_sdk/compiler/quilc.pyi
- crates/python/src/compiler/quilc.rs
- crates/python/tests/compiler/test_quilc.py
Addresses https://github.com/rigetti/pyquil/issues/1497
Closes #279
> feat: add methods for quil-c `conjugate_pauli_by_clifford` and `generate_randomized_benchmarking_sequence`

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/examples/delayed_job_retrieval.rs
- crates/lib/examples/execute.rs
- crates/lib/examples/local.rs
- crates/lib/examples/parametric_compilation.rs
- crates/lib/examples/quil_t.rs
- crates/lib/src/executable.rs
- crates/lib/src/qpu/api.rs
- crates/lib/src/qpu/execution.rs
- crates/lib/src/qpu/result_data.rs
- crates/lib/src/qpu/translation.rs
- crates/lib/tests/mocked_qpu.rs
- crates/python/src/executable.rs
- crates/python/src/grpc/models/controller.rs
- crates/python/src/grpc/models/mod.rs
- crates/python/src/grpc/models/translation.rs
- crates/python/src/qpu/api.rs
- crates/python/src/qpu/translation.rs
- deny.toml
Updates dependencies to their newest versions.
A Rust test failed once but it wasn't clear why, so I added a message to print when the assertion fails, but the test succeeded when I ran it again 🤷🏻 
I was also getting warnings about `poetry.lock` being outdated, so I ran `poetry lock --no-update`, which looks like it just updated the hash of the Python library.
> chore: update dependencies

- .github/workflows/release-library.yml
- .github/workflows/release-python.yml
- crates/python/Cargo.toml
There were two main issues at play here.
For the library crate, the `katyo/publish-crates` action was outdated and didn't support workspace dependencies. ~Fixed by updating the action, I also had to explicitly set the version of `qcs` in the Python crate to get past a cargo error.~ Turned out to be easier to replace the action with a simple call to `cargo publish`.
For both the library crate and Python package, `zmq` was failing to build on linux without the `-std=c++11` flag. Fixed by setting the `CXXFLAGS` env variable for those build steps.
Here is an example of both pipelines passing with said fixes:
* [Release Rust](https://github.com/rigetti/qcs-sdk-rust/actions/runs/4835045064)
* [Release Python](https://github.com/rigetti/qcs-sdk-rust/actions/runs/4834900147)
> CI: Fix Release Pipelines

- Cargo.lock
tracing 0.1.38 was yanked, so pointing the lockfile to 0.1.37 instead.
> build: fix tracing version

- Cargo.lock
- Cargo.toml
- crates/lib/src/qpu/client.rs
As of `qcs-api-client-common` `0.6.6`, `ClientConfiguration` respects the value of environment variable overrides as the default value. Including these changes here allows users to initialize a default `QCSClient` that doesn't require a full blown QCS configuration but still uses overrides from the environment. This is useful for users who just want to use `quilc` and/or the `qvm`. They may not have a QCS config, but they still may set the `QCS_APPLICATIONS_QVM_URL` or `QCS_APPLICATIONS_QUILC_URL` environment variables and expect them to work.
> feat: the default QCS Client configuration now respects environment variable overrides

- crates/python/src/executable.rs
- crates/python/src/py_sync.rs
- crates/python/src/qpu/client.rs
Fixes https://github.com/rigetti/qcs-sdk-rust/issues/283
Instead of blocking on a spawned thread, continually check the thread status and `py.check_signals`. Only block the main thread when the spawned thread is ready.
The async counterpart functions already support `Ctrl-C`.
To test this, run the following without having quil-c running (so that requests hang):
```sh
cd crates/python
poetry shell
maturin develop
python -m asyncio
```
and then in the python shell, try both of these
```py
from qcs_sdk.compiler.quilc import get_version_info, get_version_info_async
get_version_info()
await get_version_info_async()
```
Originally this was paired with an update to make the zmq client async, but that isn't actually necessary.
> fix(python): check signals before blocking thread

- crates/lib/src/executable.rs
- crates/lib/src/qvm/api.rs
- crates/lib/src/qvm/execution.rs
- crates/lib/src/qvm/mod.rs
- crates/lib/tests/qvm_api.rs
- crates/python/qcs_sdk/qvm/__init__.pyi
- crates/python/qcs_sdk/qvm/api.pyi
- crates/python/src/qvm/api.rs
- crates/python/src/qvm/mod.rs
There wasn't a good way to set a timeout on QVM requests, so I created an options struct, similar to how we handle it for quilc.
> feat!: QVM timeout can now be configured via a new options parameter

- Cargo.lock
- crates/lib/Cargo.toml
- crates/python/Cargo.toml
- crates/python/README.md
- crates/python/qcs_sdk/__init__.pyi
- crates/python/src/lib.rs
- crates/python/src/py_sync.rs
- crates/python/tests/logging.py
More detailed logs can be retrieved by setting the log level to `INFO` or lower.
This is implemented via `pyo3_log`, which integrates with Rust's `log`. On the Rust side, we enable the `log` feature of `tracing` so it also emits its logs to `log`.
> feat(python): Integrate with logging

- crates/python/qcs_sdk/qvm/api.pyi
- crates/python/src/qvm/api.rs
In `pyo3`, all trailing `Option<T>` parameters are supposed to optional parameters on the Python side, but I think the way we were wrapping these with sync/async macro might be conflicting with that behavior. Either way, overriding them explicitly fixed the issue.
> fix(py): The `options` parameter on QVM requests is now optional.

- crates/lib/src/compiler/isa/qubit.rs
A default fidelity of 0.0 is used instead.
> fix: The MissingQubitBenchmark error has been demoted to a warning.

- crates/python/qcs_sdk/qpu/api.pyi
- crates/python/src/qpu/api.rs
> feat(python): Broaden ExecutionOptions timeout_seconds type to float, add getters for options.

- crates/python/pyproject.toml
- crates/python/qcs_sdk/compiler/__init__.py
- crates/python/qcs_sdk/qpu/__init__.py
- crates/python/qcs_sdk/qvm/__init__.py
When we [added these lines](https://github.com/rigetti/qcs-sdk-rust/blob/main/crates/python/qcs_sdk/__init__.py#L7-L8) I believe we clobbered something that allowed the `compiler` `qpu` and `qvm` modules to be recognized as packages. Fixed by following typical Python convention, and adding an `__init__.py` for each package.
> fix(py): The `compiler`, `qpu`, and `qvm` submodules are now packages again

- Cargo.lock
- Cargo.toml
This imports the updated `qcs-api-client` libraries.
> chore: update qcs-api-client libraries

- crates/lib/src/qpu/api.rs
This enables using different protobuf types rather than the ones the SDK makes available.
> Add a public method to get a GRPC connection without specifying the API

- .github/workflows/release-python.yml
- Cargo.toml
closes #366 
Tested some recommendations from the Rust [min-sized-guide](https://github.com/johnthagen/min-sized-rust) to see how they affected binary size.
I think we should use LTO with codegen-units=1. It has a decent impact on the binary size, and we use it in quil-rs already for the performance.
I also don't see any harm in stripping symbols, but I could be convinced otherwise. I'm not sure if they'd ever be useful in practice, as we can just re-build with symbols from a buggy version if we really needed them and I don't think we'd expect users to want to load release wheels into a debugger.
Out of interest, I also tested `-Oz` and aborting on panics. These negatively impact performance and functionality, so they aren't good for our use case, but I was curious to see how much of an …
> build: Use a release profile that reduces binary size

- clippy.toml
- crates/lib/src/client.rs
- crates/lib/src/qpu/api.rs
> feat: add a type alias for 'generic' gRPC connections

- crates/lib/src/executable.rs
- crates/lib/src/qpu/execution.rs
Seems that it was intended to require the crate's wrapper for `TranslationOptions`, otherwise the consumer needs to separately install [qcs-api-client-grpc](https://crates.io/crates/qcs-api-client-grpc) to call `submit_to_qpu` https://github.com/rigetti/qcs-sdk-rust/blob/6416c87861583ee0ea0f5ff66c4daa049ac4f14b/crates/lib/src/executable.rs#L540
https://github.com/rigetti/qcs-sdk-rust/blob/c6ec8c4271b6c01c620974722e10d31684b58416/crates/lib/src/qpu/translation.rs#L120
This change will bring things in-line with the python counterpart https://github.com/rigetti/qcs-sdk-rust/blob/c6ec8c4271b6c01c620974722e10d31684b58416/crates/python/src/qpu/translation.rs#L172 https://github.com/rigetti/qcs-sdk-rust/blob/c6ec8c4271b6c01c620974722e10d31684b58416/crates/python/src/qpu/translation.rs#L109
> fix!: use crate-defined translation options

- crates/lib/src/executable.rs
Up for debate, but in cases where you need to provide some execution configuration, it would help to use a single source of truth for the qcs client
For example, to use https://github.com/rigetti/qcs-sdk-rust/blob/a4c832ca7360d546a0bd0c71230353f6a4b28eaa/crates/lib/src/executable.rs#L367 
Here's what you have to do:
```rust
// ... in some other function ...
let exe = qcs::executable::Executable::from_quil("...");
// ... later on ...
// > before this change: who knows if `exe` is configured with
// the same client or if we're doing a redundant load
let qcs_client = qcs::client::Qcs::load().await;
// > after this change: same client, only one load
let qcs_client = exe.get_qcs_client().await;
let qvm_client = qcs::qvm::http::HttpClient::from(&qcs_client);
exe.execute_on_qvm(&qvm_client)
```
> feat: make Executable.get_qcs_client public

- crates/lib/src/compiler/quilc.rs
When the `QuilcConnection` error occurs, the resulting error message is vague and doesn't give a hint towards what the issue might be if you know your `quilc` server is running at the right port. For example, this is how the error manifests in `quil-py`:
```
quilc.QuilcError: Problem connecting to quilc at tcp://127.0.0.1:5555
```
This PR appends the RPCQ error to the message and hopefully adds a bit more context and gives a better hint at what might be going wrong.
> feat: Improve error message when a quilc connection fails.

- crates/lib/src/compiler/rpcq.rs
> fix: The quilc RPCQ client is now safe to share between threads.

- Cargo.lock
- Cargo.toml
- crates/lib/src/compiler/quilc.rs
- crates/lib/src/qpu/rewrite_arithmetic.rs
- crates/lib/src/qpu/translation.rs
- crates/python/qcs_sdk/qpu/translation.pyi
- crates/python/src/qpu/translation.rs
Resolves #406.
This refactors the SDK `TranslationOptions` to add methods to set gRPC options without needing to deal with the `prost` types.
> feat!: expose BackendV2 options through Python

- Cargo.lock
- Cargo.toml
- crates/lib/src/qpu/api.rs
- crates/python/qcs_sdk/qpu/api.pyi
- crates/python/src/qpu/api.rs
Closes #414 
Allows the new proto `ExecutionOptions` to be configured, embedded within the existing `ExecutionOptions`.
> feat: provide ExecutionOptions configurability as ApiExecutionOptions

- .github/workflows/release-python.yml
closes #421 
This repo has been setup as a trusted publisher for qcs-sdk-python in PyPI. I've modified the workflow per the [maturin documentation](https://www.maturin.rs/distribution.html?highlight=trusted%20p#using-pypis-trusted-publishing).
> ci: Use trusted publishing for PyPI

- Cargo.lock
- Cargo.toml
- deny.toml
quil-rs [has a fix](https://github.com/rigetti/quil-rs/pull/338) for `DEFCIRCUIT` serialization
> fix: bump quil-rs versions

- Cargo.lock
- Cargo.toml
- crates/lib/src/qpu/api.rs
- crates/python/qcs_sdk/qpu/api.pyi
- crates/python/src/qpu/api.rs
closes #446 
I've decided to not implement this as part of the Executable API. The Executable API maintains state for a single set of parameters, so adding support for multiple sets would lead to a breaking change.
> feat: Support running a program with multiple sets of patch values in a single request.

- Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2024-0332
> fix: update h2, see RUSTSEC-2024-0332

- clippy.toml
- crates/lib/src/client.rs
- crates/lib/src/compiler/libquil.rs
- crates/lib/src/compiler/quilc.rs
- crates/lib/src/qpu/api.rs
- crates/lib/src/qpu/rewrite_arithmetic.rs
- crates/python/src/execution_data.rs
Increases the gRPC max message size from 4MB (the `tonic` default) to 50MB. This is motivated by some users having hit the 4MB limit.
This MR also fixes a number of new clippy lints that were causing CI to fail.
Closes #467.
> feat: increase gRPC max message size from 4MB to 50MB

- Cargo.lock
- Cargo.toml
In rigetti/rigetti-pyo3#45 (and rigetti/rigetti-pyo3#46), I moved all references to the Python time types under the "time" feature.  This was a bugfix, but I didn't realize it was also a breaking change – any library that relied on the time types implicitly being available would break, just as this one did!  This adds the missing feature dependency, and I've also upgraded rigetti/rigetti-pyo3#46 to be a breaking change.
This commit also updates Cargo.lock to force the update to rigetti-pyo3, meaning that builds will fail without the substantive change.
Closes #475.
> fix: add explicit dependency on rigetti-pyo3's "time" feature

- Cargo.lock
- Cargo.toml
- crates/lib/examples/delayed_job_retrieval.rs
- crates/lib/examples/execute.rs
- crates/lib/examples/local.rs
- crates/lib/examples/parametric_compilation.rs
- crates/lib/examples/quil_t.rs
- crates/lib/src/client.rs
- crates/lib/src/compiler/quilc.rs
- crates/lib/src/diagnostics.rs
- crates/lib/src/executable.rs
- crates/lib/src/qpu/api.rs
- crates/lib/src/qvm/execution.rs
- crates/lib/tests/basic_qvm.rs
- crates/lib/tests/mocked_qpu.rs
- crates/lib/tests/parametric_compilation.rs
- crates/lib/tests/qvm_api.rs
- crates/python/qcs_sdk/client.pyi
- crates/python/src/client.rs
- crates/python/src/qpu/api.rs
- crates/python/src/qpu/isa.rs
- crates/python/src/qpu/mod.rs
- crates/python/src/qpu/translation.rs
- crates/python/tests/test_client.py
- deny.toml
This will close #482
If you add the following to `Cargo.toml`, which is done during wheel publishing
```toml
[patch.crates-io]
hyper-proxy = { git = "https://github.com/rigetti/hyper-proxy" }
```
You'll see there's no dependency on the old ring version anymore
```sh
$ cargo tree -i ring@0.16.20
error: package ID specification `ring@0.16.20` did not match any packages
Did you mean one of these?
ring@0.17.8
```
> fix!: update qcs-api deps to use a >=9 version of jsonwebtoken

- crates/python/pyproject.toml
- crates/python/src/qpu/api.rs
- crates/python/tests/qpu/test_api.py
This is to support rigetti/pyQuil#1719
> feat(python): ConnectionStrategy supports the pickle module

- Cargo.lock
- crates/lib/Makefile.toml
- crates/python/Makefile.toml
- deny.toml
closes #496; cargo-deny recently shipped breaking changes to their deny.toml spec, so I've updated ours to match.
> ci: Update deny.toml to match new specification

- crates/python/src/compiler/quilc.rs
- crates/python/src/executable.rs
- crates/python/src/qpu/api.rs
- crates/python/src/qpu/translation.rs
- crates/python/src/qvm/api.rs
- crates/python/src/qvm/mod.rs
The default behavior or `pypropagate` is to eprintln errors - this includes the case where any upstream packages don't have Python `opentelemetry` installed. This doesn't actually raise, but it is noisy and annoying.
This changes the behavior to ignore context propagation failures. In the future, I'll support some more discerning options, so for instance import errors can be ignored (as they most often should), but any other error can be raise.
> fix: ignore context extraction failure

- crates/lib/src/qpu/api.rs
> fix: ExecutionOptions::default() now respects defaults used in ExecutionOptionsBuilder::default()

- crates/lib/src/lib.rs
> fix: re-export quil-rs so that downstream crates can avoid version conflicts

- Cargo.lock
- crates/lib/Cargo.toml
- crates/lib/src/executable.rs
- crates/lib/src/qpu/api.rs
- crates/python/Cargo.toml
- crates/python/qcs_sdk/_tracing_subscriber/common/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/common/__init__.pyi
- crates/python/qcs_sdk/_tracing_subscriber/layers/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/layers/__init__.pyi
- crates/python/qcs_sdk/_tracing_subscriber/layers/file/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/layers/file/__init__.pyi
- crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp/__init__.pyi
- crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp_file/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp_file/__init__.pyi
- crates/python/qcs_sdk/_tracing_subscriber/subscriber/__init__.py
- crates/python/qcs_sdk/_tracing_subscriber/subscriber/__init__.pyi
- crates/python/qcs_sdk/qpu/api.pyi
- crates/python/src/qpu/api.rs
> Expose api execution options timeout ii

- .github/workflows/checks.yml
- .github/workflows/prepare-release.yml
- .github/workflows/publish-docs.yml
- .github/workflows/release-dry-run.yml
- .github/workflows/release-library.yml
- .github/workflows/release-python.yml
- Cargo.lock
- crates/python/Makefile.toml
Closes #518.
Includes updates to Rust dependencies in order to prompt a version bump on merge.
> ci: update github actions and macos runner

- .github/workflows/prepare-release.yml
- .github/workflows/release-dry-run.yml
Recently #519 failed because of https://github.com/knope-dev/action/issues/10
This fixes that by using the compatible https://github.com/knope-dev/knope/releases/tag/v0.7.2 tag
> chore: update github actions knope version to 0.7.2

- .github/action-common-python-release/action.yml
- .github/workflows/release-python.yml
Should fix <html><body><a href="https://github.com/rigetti/qcs-sdk-rust/actions/runs/13041993520">[python 0.21.7 · rigetti/qcs-sdk-rust@dcd5f1e](https://github.com/rigetti/qcs-sdk-rust/actions/runs/13041993520)</a></body></html>
```
Error: This request has been automatically failed because
it uses a deprecated version of `actions/download-artifact: v3`.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
> fix(python): update workflow action version for download/upload artifact

- .github/action-common-python-release/action.yml
- .github/workflows/check-release-python.yml
- .github/workflows/check-release-python.yml.disabled
- .github/workflows/release-python.yml
https://github.com/rigetti/qcs-sdk-rust/pull/532 wheels apparently aren't building correctly in `python 3.9` this will at least test installing them in all environments.
> fix: test all python releases individually, use manylinux 2_34

- .github/workflows/release-python.yml
- Cargo.lock
- crates/python/pyproject.toml
- deny.toml
Still attempting to get to the bottom of https://github.com/rigetti/qcs-sdk-rust/issues/531
> fix(python): update and sync maturin versions between build and upload

- .github/action-common-python-release/action.yml
- .github/workflows/release-python.yml
Update some actions versions to (hopefully) reduce warning spam, and set upload-artifacts compression level to 0
> fix(python): don't use compression when storing github actions artifacts

- .github/workflows/release-python.yml
This should ensure that if a release fails for one target configuration, it doesn't affect the other configurations for that target.
In particular, Linux is the only platform for which we've separated the grpc-web releases from the "vanilla" releases, and since the grpc-web build is [currently failing](https://github.com/rigetti/qcs-sdk-rust/issues/549), this means that for non-Linux targets, the grpc-web build failure prevents non-grpc-web configurations from being released.
> chore: disable 'fail-fast' on each platform
