qcs/src/qpu/quilc/isa/qubit.rs, qcs/tests/compiler-isa-Aspen-8.json
=> fix: Sync RZ fidelity with pyQuil implementation.

src/configuration/mod.rs, src/configuration/secrets.rs, src/configuration/settings.rs, src/executable.rs, src/execution_data.rs, src/qpu/execution.rs, src/qpu/mod.rs, src/qpu/quilc/isa/edge.rs, src/qpu/quilc/isa/mod.rs, src/qpu/quilc/isa/operator.rs, src/qpu/quilc/isa/qubit.rs, src/qpu/quilc/mod.rs, src/qpu/rewrite_arithmetic.rs, src/qpu/rpcq.rs, src/qpu/runner.rs, src/qvm/execution.rs, src/qvm/mod.rs, src/register_data.rs
=> feat: derive more traits on types

.github/workflows/release-dry-run.yml, .github/workflows/release.yml
=> ci: delete knope artifacts before cargo publish

Cargo.lock, Cargo.toml, crates/lib/Cargo.toml, crates/lib/src/api.rs, crates/lib/src/executable.rs, crates/lib/src/qpu/execution.rs, crates/lib/src/qpu/rewrite_arithmetic.rs, crates/lib/src/qvm/execution.rs, crates/python/src/lib.rs
Does what it says on the tin. `quil-rs` has had some breaking changes which are fixed herein. Mostly this required updating/improving errors.
=> feat: upgrade quil-rs dependency and fix issues

.github/workflows/release-library.yml, .github/workflows/release-python.yml
This is not a code change, but is marked `fix:` to trigger a release
=> fix: install protoc in github actions

.github/workflows/release-python.yml
Hopefully this fixes the issue where protoc isn't found in PATH :shrug:
=> fix: move protoc install action to later

crates/python/qcs_sdk.pyi
See #198
Missed removing the type annotations
=> fix(python): remove awaitable annotation on async functions

Cargo.lock, crates/lib/Cargo.toml, crates/lib/src/api.rs, crates/lib/src/qpu/quilc/mod.rs, crates/python/qcs_sdk.pyi, crates/python/src/lib.rs, crates/python/tests/conftest.py, crates/python/tests/qcs_config/secrets.toml, crates/python/tests/qcs_config/settings.toml, crates/python/tests/test_api.py
=> feat: add method for getting the version of the running quilc server

crates/lib/src/api.rs, crates/lib/src/executable.rs, crates/lib/src/execution_data.rs, crates/lib/src/lib.rs, crates/lib/src/qpu/client.rs, crates/lib/src/qpu/execution.rs, crates/lib/src/qpu/mod.rs, crates/lib/src/qpu/quilc/isa/mod.rs, crates/lib/src/qpu/quilc/mod.rs, crates/lib/src/qpu/rewrite_arithmetic.rs, crates/lib/src/qpu/rpcq.rs, crates/lib/src/qpu/runner.rs, crates/lib/src/qvm/mod.rs
Resolves #217.
Added a suite of lints to try to help catch this sort of thing in the future.
=> Make public types actually public, etc.

Cargo.lock, crates/lib/src/api.rs
Resolves #210.
This is based on #219 to avoid creating conflicts with it.
=> Add Send + Sync to dynamic errors

.github/workflows/prepare-release.yml
=> ci: update knope to 0.7.0 with version detection fixes

crates/lib/src/api.rs, crates/python/qcs_sdk/api.pyi, crates/python/src/api.rs
=> feat: export get_quilt_calibrations

crates/lib/src/qpu/quilc/mod.rs, crates/python/qcs_sdk/api.pyi, crates/python/src/api.rs
Fixes https://github.com/rigetti/qcs-sdk-rust/pull/204 since I broke it with https://github.com/rigetti/qcs-sdk-rust/pull/241 (sorry @notmgsk)
Closes #242
=> feat: support protoquil flag in compilation (rebase fix)

Cargo.lock, Cargo.toml, crates/lib/src/compiler/isa/edge.rs, crates/lib/src/compiler/isa/mod.rs, crates/lib/src/compiler/isa/operator.rs, crates/lib/src/compiler/isa/qubit.rs, crates/lib/src/executable.rs, crates/lib/src/qpu/client.rs, crates/lib/src/qpu/rewrite_arithmetic.rs, crates/python/src/qpu/client.rs, crates/python/src/qpu/isa.rs
Recent releases of the API clients introduced breaking changes. This updates the SDK to adapt to those changes.
@notmgsk I rebased this branch off of `main` because there were conflicts. I don't think anything got removed from what you did, but you'll have to let me know.
=> Api client error breaking change

crates/lib/Makefile.toml, crates/lib/src/qpu/api.rs, crates/lib/src/qpu/execution.rs
=> fix: fix broken tracing after merge conflicts

crates/lib/src/client.rs, crates/lib/src/compiler/quilc.rs, crates/lib/src/executable.rs, crates/lib/src/lib.rs, crates/lib/src/qpu/api.rs, crates/lib/src/qpu/execution.rs, crates/lib/src/qpu/mod.rs, crates/lib/src/qpu/translation.rs, crates/lib/src/qvm/execution.rs, crates/lib/tests/basic_qvm.rs, crates/lib/tests/parametric_compilation.rs, crates/python/qcs_sdk/__init__.pyi, crates/python/qcs_sdk/client.pyi, crates/python/qcs_sdk/compiler/quilc.pyi, crates/python/qcs_sdk/qpu/__init__.pyi, crates/python/qcs_sdk/qpu/api.pyi, crates/python/qcs_sdk/qpu/isa.pyi, crates/python/qcs_sdk/qpu/translation.pyi, crates/python/src/client.rs, crates/python/src/compiler/quilc.rs, crates/python/src/executable.rs, crates/python/src/lib.rs, crates/python/src/qpu/api.rs, crates/python/src/qpu/isa.rs, crates/python/src/qpu/mod.rs, crates/python/src/qpu/translation.rs, crates/python/tests/test_client.py
=> feat!: Loading a Qcs Client is now infallible and is the primary client used throughout the library.

crates/python/src/py_sync.rs, crates/python/src/qpu/translation.rs
This fixes an issue were certain synchronous variants of functions exported by `py_function_sync_async!` were hanging indefinitely.
After some experimenting, I narrowed down the issue to `std::thread::sleep`. It doesn't appear to consistently yield CPU time to to other threads.
This naturally led me to `tokio::time::sleep`, which is async and needs to be awaited. I wrapped everything up in a `tokio::select!` statement, which I was worried about as first, since `py.check_signals` needs to run on the main thread to work. However, [the docs state](https://docs.rs/tokio/latest/tokio/macro.select.html#runtime-characteristics) that `select!` runs tasks concurrently on the same thread, and as long as a task isn't `spawn`ed, it will get scheduled on the main thread.
=> fix(python): The translate function no longer hangs infinitely

crates/lib/src/client.rs
=> fix: Increase gRPC message size limit

Cargo.lock, Cargo.toml, crates/lib/Cargo.toml, crates/lib/src/qpu/rewrite_arithmetic.rs, crates/lib/src/qpu/snapshots/qcs__qpu__rewrite_arithmetic__describe_rewrite_arithmetic__it_converts_frequency_expressions.snap, crates/lib/src/qvm/mod.rs, deny.toml
=> chore: update quil-rs

Cargo.lock, Cargo.toml, crates/python/pyproject.toml
Updates quil-rs, which includes a few parsing fixes.
=> feat: update quil-rs

Cargo.lock, crates/lib/src/qpu/translation.rs, crates/python/qcs_sdk/qpu/translation.pyi, crates/python/src/qpu/translation.rs, crates/python/tests/qpu/test_translation.py
=> feat(python): provide access to the translation backend option

.github/workflows/release-python.yml, Cargo.lock, Cargo.toml, crates/lib/src/qpu/execution.rs, crates/python/pyproject.toml
=> feat(python): Support Python 3.12

Cargo.lock, Cargo.toml
This propagates the fix to rigetti/quil-rs#315 by pulling in the new version.
=> fix: update quil-rs to get string serialization bugfix

Cargo.toml, crates/python/pyproject.toml
Updating quil-rs/py to the latest version so the latest features are available to consumers.
=> feat: Update quil-rs/py to 0.23.3/0.6.3

.gitignore, crates/lib/src/executable.rs, crates/lib/src/qpu/api.rs, crates/lib/src/qpu/execution.rs, crates/lib/src/qpu/translation.rs, crates/python/qcs_sdk/qpu/api.pyi, crates/python/src/qpu/api.rs
=> feat: Jobs that have yet to begin executing can be cancelled.

Cargo.lock, Cargo.toml, crates/lib/Cargo.toml, crates/python/pyproject.toml
=> feat: Update quil

Cargo.lock, Cargo.toml, clippy.toml, crates/lib/src/compiler/quilc.rs, crates/lib/src/qpu/api.rs
=> fix: Refresh JWT only when expired, not before every request

Cargo.lock, deny.toml
=> Allow Unicode 3.0 license

Cargo.lock, Cargo.toml, crates/lib/src/executable.rs, crates/python/pyproject.toml, crates/python/src/qpu/api.rs
This is to support [pyQuil#1719](https://github.com/rigetti/pyquil/issues/1719)
=> feat(python): ExecutionOptions supports the pickle module.

Cargo.lock, Cargo.toml, crates/lib/src/compiler/isa/qubit.rs, crates/python/.stubtest-allowlist, crates/python/pyproject.toml, crates/python/qcs_sdk/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/common/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/layers/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/layers/file/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/layers/otel_otlp_file/__init__.pyi, crates/python/qcs_sdk/_tracing_subscriber/subscriber/__init__.pyi, crates/python/qcs_sdk/client.pyi, crates/python/qcs_sdk/compiler/__init__.pyi, crates/python/qcs_sdk/compiler/quilc.pyi, crates/python/qcs_sdk/qpu/__init__.pyi, crates/python/qcs_sdk/qpu/api.pyi, crates/python/qcs_sdk/qpu/isa.pyi, crates/python/qcs_sdk/qpu/translation.pyi, crates/python/qcs_sdk/qvm/__init__.pyi, crates/python/qcs_sdk/qvm/api.pyi, crates/python/tests/conftest.py, crates/python/tests/qpu/test_isa.py
=> fix: bump qcs-api-client versions to allow get_instruction_set_architecture without authentication
